name: appsonair_flutter_appsync
description: AppsOnAir AppSync flutter sdk enables you to configure the version update of your app directly through AppsOnAir.
version: 0.0.1

#homepage:
repository: https://github.com/apps-on-air/AppsOnAir-flutter-AppSync

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lwpackage.appsonair_flutter_appsync
        pluginClass: AppsonairFlutterAppsyncPlugin
      ios:
        pluginClass: AppsonairFlutterAppsyncPlugin

    
 