name: appsonair_flutter_appsync
description: The AppsOnAir AppSync Flutter SDK lets you manage forced and regular app updates, as well as enable maintenance mode, directly via AppsOnAir.
version: 0.0.2

#homepage:
repository: https://github.com/apps-on-air/AppsOnAir-flutter-AppSync

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lwpackage.appsonair_flutter_appsync
        pluginClass: AppsonairFlutterAppsyncPlugin
      ios:
        pluginClass: AppsonairFlutterAppsyncPlugin

    
 